[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  h2zero/NimBLE-Arduino @ ^2.3.6
  https://github.com/lemmingDev/ESP32-BLE-Gamepad.git#v0.7.3
